### PR TITLE
added listmaps command

### PR DESCRIPTION
**Pull request by JoBergeron**
Added command 'listmaps' to list available maps to load through the console. It will list maps in pak files first followed by maps in the 'maps/' folder from baseq2 or mod or expansion being played.

q2_0000

### CODE REVIEW

**Comment by Yamagi** [comment]
Hi,
that's a very nice idea. The code looks good an I'm going to merge it. But can you add the command to the documentation in https://github.com/yquake2/yquake2/blob/master/doc/050_commands.md ?

**Comment by Yamagi** [comment]
And what about sorting the list?

**Comment by JoBergeron** [comment]
I'm not sure how we should sort this. At the moment, the the maps that 
come from paks will listed in their order of appearence in their pak. 
Files that are stored in the maps/ folder will be appear in a 
alphabetically sort manner.

In the screenshot provided with my pull request. Maps listed from 
'mine1' to 'boss2' are maps from the baseq2 pak files. 'angron1a' and 
'angron1b' are custom maps which are present in the 'maps/' subdirectory 
in baseq2.

I feel this is fine because users of this command will probably be 
interested in listing the map names from their maps/ folder to know 
which custom map to load. If there's a better idea on the overall 
sorting though, I'd be glad to give it a go on the implementation side.

**Comment by JoBergeron** [comment]
> 
> 
> Hi,
> that's a very nice idea. The code looks good an I'm going to merge it. But can you add the command to the documentation in https://github.com/yquake2/yquake2/blob/master/doc/050_commands.md ?

Yes I will add it there!

**Comment by Yamagi** [comment]
> I feel this is fine because users of this command will probably be interested in listing the map names from their maps/ folder to know which custom map to load.

You're right. Sorting the entries would require a fair amount of copying the strings, etc. Let's leave things as they are.

**Comment by Yamagi** [comment]
And merged. Thank you! :)

**Pull request merged**
