### PR TITLE
Add particle square support

### PR DESCRIPTION
**Pull request by 0lvin**
* square particle support
* resize staging buffers

### CODE REVIEW

**Comment by Yamagi** [comment]
Cool. I just gave a it short try. In think with this we're at the point that we can provide official test builds with Vulkan support. :)

Before I merged this... I get this crash at shutdown. It only happens with the Vulkan renderer, not the other. It looks like a bug somewhere in SDL2 or maybe Xorg. @DanielGibson, have you seen something like this before?

```
Thread 1 "quake2" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b82f51 in unlink_chunk.isra () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7b82f51 in unlink_chunk.isra () from /usr/lib/libc.so.6
#1  0x00007ffff7b84065 in _int_free () from /usr/lib/libc.so.6
#2  0x00007ffff47446f5 in _XFreeDisplayStructure () from /usr/lib/libX11.so.6
#3  0x00007ffff4732323 in XCloseDisplay () from /usr/lib/libX11.so.6
#4  0x00007ffff7dca091 in ?? () from /usr/lib/libSDL2-2.0.so.0
#5  0x00007ffff7d940b9 in ?? () from /usr/lib/libSDL2-2.0.so.0
#6  0x00007ffff7d015cb in ?? () from /usr/lib/libSDL2-2.0.so.0
#7  0x0000555555599282 in GLimp_Shutdown () at src/client/vid/glimp_sdl.c:429
#8  0x00005555555cc5b9 in Sys_Quit () at src/backends/unix/system.c:87
#9  0x000055555559e255 in Com_Quit () at src/common/clientserver.c:289
#10 0x000055555556d1ee in CL_Quit_f () at src/client/cl_main.c:314
#11 0x00005555555a2ab3 in Cbuf_Execute () at src/common/cmdparser.c:229
#12 0x000055555556e276 in CL_Frame (packetdelta=16774, renderdelta=<optimized out>, timedelta=<optimized out>, 
    packetframe=true, renderframe=true) at src/client/cl_main.c:785
#13 0x00005555555a89f7 in Qcommon_Frame (usec=16774) at src/common/frame.c:630
#14 0x00005555555a8c2c in Qcommon_Mainloop () at src/common/frame.c:165
#15 0x00005555555a926c in Qcommon_Init (argc=3, argv=0x7fffffffe828) at src/common/frame.c:381
#16 0x000055555555df21 in main (argc=3, argv=0x7fffffffe828) at src/backends/unix/main.c:140
(gdb) up 7
#7  0x0000555555599282 in GLimp_Shutdown () at src/client/vid/glimp_sdl.c:429
429			SDL_QuitSubSystem(SDL_INIT_VIDEO);
(gdb) list
424		{
425			SDL_Quit();
426		}
427		else
428		{
429			SDL_QuitSubSystem(SDL_INIT_VIDEO);
430		}
431	
432		ClearDisplayIndices();
433	}
```

**Comment by DanielGibson** [comment]
Nope, doesn't look familiar

**Comment by 0lvin** [comment]
Look like error is sporadic and related to some data race? It happens sometime, and I can't provide exact steps for reproduce. I have tried to catch error by valgrind, but without any success for now. 

Whole back trace was: 
```
Thread 1 "quake2" received signal SIGSEGV, Segmentation fault.
unlink_chunk (p=p@entry=0x555556f34a70, av=0x7ffff7d00b80 <main_arena>) at malloc.c:1459
1459      if (__builtin_expect (fd->bk != p || bk->fd != p, 0))
(gdb) bt
#0  unlink_chunk (p=p@entry=0x555556f34a70, av=0x7ffff7d00b80 <main_arena>) at malloc.c:1459
#1  0x00007ffff7bcacf5 in _int_free (av=0x7ffff7d00b80 <main_arena>, p=0x555556f34a70, have_lock=<optimized out>) at malloc.c:4333
#2  0x00007ffff78e64f8 in _XFreeDisplayStructure () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff78d3bf1 in XCloseDisplay () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff7de4541 in X11_DeleteDevice (device=0x555556f31330) at ./src/video/x11/SDL_x11video.c:116
#5  0x00007ffff7db7446 in SDL_VideoQuit_REAL () at ./src/video/SDL_video.c:2873
#6  0x00007ffff7db747f in SDL_VideoQuit_REAL () at ./src/video/SDL_video.c:2832
#7  0x00007ffff7d2909a in SDL_QuitSubSystem_REAL (flags=16416) at ./src/SDL.c:317
#8  0x00005555555ab5c6 in GLimp_Shutdown () at src/client/vid/glimp_sdl.c:435
#9  0x00005555555b03c6 in VID_Shutdown () at src/client/vid/vid.c:522
#10 0x0000555555572a51 in CL_Shutdown () at src/client/cl_main.c:945
#11 0x00005555555f4f5f in Sys_Quit () at src/backends/unix/system.c:87
#12 0x00005555555b1445 in Com_Quit () at src/common/clientserver.c:289
#13 0x00005555555716ea in CL_Quit_f () at src/client/cl_main.c:314
#14 0x00005555555901c9 in M_Quit_Key (key=121) at src/client/menu/menu.c:4558
#15 0x00005555555904b2 in M_Keydown (key=121) at src/client/menu/menu.c:4654
#16 0x000055555557012b in Char_Event (key=121) at src/client/cl_keyboard.c:1108
#17 0x0000555555585515 in IN_Update () at src/client/input/sdl.c:512
#18 0x0000555555572793 in CL_Frame (packetdelta=24777, renderdelta=24777, timedelta=24777, packetframe=true, renderframe=true) at src/client/cl_main.c:784
#19 0x00005555555bef80 in Qcommon_Frame (usec=24777) at src/common/frame.c:632
#20 0x00005555555be30b in Qcommon_Mainloop () at src/common/frame.c:165
#21 0x00005555555be9c5 in Qcommon_Init (argc=1, argv=0x7fffffffe268) at src/common/frame.c:383
#22 0x00005555555f2e4f in main (argc=1, argv=0x7fffffffe268) at src/backends/unix/main.c:140
```

**Comment by Yamagi** [comment]
I gave it a try with Address Sanitizer enabled. As far I can tell from about 20 runs with AMD, Intel and Nvidia GPUs we don't have a memory corruption somewhere in our code; at least Address Sanitizer doesn't trigger. Interestingly I can reproduce the crash to nearly 100% on my desktop with an about 6 weeks old Arch Linux and an Radeon 5770 XT but I have never seen it on my Laptop with an Intel GPU. I'll update the desktop sometime next week and see if it's still a problem with newer packages. There're at least some crash fixes in Mesa / RADV that I don't have.

**Comment by Yamagi** [comment]
After I've updates my system the problem is gone. So it was really some bug in one of the libraries, either in xorg itself or Mesa.

**Comment by Yamagi** [comment]
And finally merged. :)

**Pull request merged**
