### PR TITLE
 Vulkan improvements

### PR DESCRIPTION
**Pull request by 0lvin**
* Fix multiplayer -> player setup menu rendering
* Cinema scaling with near color filtering

### CODE REVIEW

**Comment by runlevel5** [comment]
@0lvin would you be able to provide screenshots or video? TIA

**Comment by 0lvin** [comment]
@runlevel5 I am not sure that difference will be visible on video, lets try ;-) 

Without filtering
[yquake2: Without filtering](http://www.youtube.com/watch?v=C2Veptq7UlA)

With filtering
[yquake2: Without filtering](http://www.youtube.com/watch?v=J6QCgwjTfMg)

**Comment by Yamagi** [comment]
The videos are looking very good now, sharp and without noticeable pixels even in high resolutions. Good work!

Can I merge this?

**Comment by 0lvin** [comment]
> Can I merge this?

Yes, it will be great :-)

**Comment by 0lvin** [comment]
7bd1973 contains fixes detected with [Martyr](https://www.moddb.com/games/quake-2/addons/martyr) where reallocated buffers   has wrong mapped flag value as result of save buffer to swap list and only after that buffer in unmapped.

**Comment by Yamagi** [comment]
And merged! Thank you!

**Comment by 0lvin** [comment]
Thank you @Yamagi

**Pull request merged**
