### PR TITLE
Fixes scale particles in soft render

### PR DESCRIPTION
**Pull request by 0lvin**
* window height as multiple for particles size.
*  Add custom particle shape by sw_custom_particles.
   0 - use rectangle (default shape)
   1 - use hexagon

### CODE REVIEW

**Comment by DanielGibson** [comment]
What does the "Add size checks for WAL load" commit do?
Or, what problem does it solve? I can't remember any bugs with invalid .wal files

**Comment by 0lvin** [comment]
@DanielGibson 
> What does the "Add size checks for WAL load" commit do?
It is only small validation code, can be usable for broken *.wal files, same checks as we have in LoadPCX when if image is too short we return error.

>   Apparently the particles always have the same size (like "4x4 px" or whatever), regardless of resolution.
Good idea, need to check.

**Comment by maraakate** [comment]
@DanielGibson: if you implement the better scaling code and it works well let me know.

**Comment by 0lvin** [comment]
@DanielGibson @maraakate Could you check? What do you think about such implementation?

**Comment by maraakate** [comment]
ill try and implement the changes to q2dos over the next couple of days.

**Comment by 0lvin** [comment]
@maraakate Also if you like - code in https://github.com/0lvin/yquake2/commits/heretic2 support load maps from heretic2 demo.  Without game logic, but enough for static objects on map.

**Comment by maraakate** [comment]
No, we're trying to keep Q2DOS relatively clean.  Superflous extensions like this won't benefit it.  Thanks though.

**Comment by DanielGibson** [comment]
The implementation looks good!
Two things however:
* I think the particles could be a bit bigger - IMO, `pix = (izi * d_pix_mul) >> 7;` looks better than shifting by 8. But this is mostly a matter of taste I guess?
* I personally like the new particle shape better - but I prefer the OpenGL renderer with filtered textures anyway. I guess the people who prefer a softrenderer also prefer the oldschool square particles. I guess if you add rounder particles, that should be configurable via cvar?

**Comment by 0lvin** [comment]
@DanielGibson  I have checked ">> 8" to ">>7" and added "sw_custom_particles" for use default particles shape.

**Comment by Yamagi** [comment]
And to me too :)

**Pull request merged**
