### PR TITLE
Bump to SDL3 gitrev 8db3b47

### PR DESCRIPTION
**Pull request by erysdren**
According to [this](https://github.com/libsdl-org/SDL/releases/tag/preview-3.1.3), SDL3's ABI will become stable soon. So I've bumped the support for yquake2.

### CODE REVIEW

**Comment by Yamagi** [comment]
You are fast :) Thank you!

**Comment by Yamagi** [comment]
I have rebased the *sdl3-current* onto *master* and - since we've got a new preview release - merged the branch back into *master*. So *sdl3-current* and *master* have now the same code, *master * requires the SDL 3.1.3 preview release to build and run.

**Comment by protocultor** [comment]
It did not compile for me until this patch was applied: [SDL_GetJoystickID.patch](https://github.com/user-attachments/files/17270277/SDL_GetJoystickID.patch)
All other instances of `SDL_JoystickInstanceID` in _SDL2_ were replaced by `SDL_GetJoystickID` in _SDL3_. Replacing that last one makes it work.

**Comment by Yamagi** [comment]
Hmpf. I have committed the patch in *master* and *sdl3-current*. Thank you :)

**Pull request merged**
