### PR TITLE
Get rid VLA

### PR DESCRIPTION
**Pull request by 0lvin**
* get rid VLA in gl1
* get rid VLA in gl3
* fix lights without current entity
* use qboolean for  r_outof... in soft render

### CODE REVIEW

**Comment by Yamagi** [comment]
I just had a look. Overall the changes look good and I can merge 3dce88e, c53d42b and 83b1ebf. But I'm very hesitant to merge memory management changes without necessity, because everytime I (or someone else) does well mend changes to anything that has to do with memory something breaks. Often in subtle, hard to debug ways.

**Comment by 0lvin** [comment]
I have checked code with [q2dq2](http://quake.speeddemosarchive.com/quake/qdq/movies/q2dq2.html) on gl1/gl3/soft renders.

**Comment by 0lvin** [comment]
@Yamagi I have moved safe commits to #382

**Comment by Yamagi** [comment]
Superseded by another PR that was merged.

**Pull request closed without merging**
