### PR TITLE
Cppcheck fixes

### PR DESCRIPTION
**Pull request by 0lvin**
* Add support retexturing for software render(disabled by default)
* code clean up by cppcheck validation
* remove `sw_maxedges`, `sw_maxsurfs` as we always reallocate buffers if see size problems.

### CODE REVIEW

**Comment by 0lvin** [comment]
@Yamagi What do you think about 9fa0f1257208ada0c3aabf05f71da0b2dd8183d3 ? It will restore all `original` API and functions. And create `itemlist` with `MAX_ITEMS` items so iteration by `itemlist` will be safe. Other changes should be without side effects(only move iteration variables to loop's).

About  `sw_retexturing` - can make game unusable because it will change contrast of textures (only 4 bits for brights value). So i prefer to save it disabled for several iteration.

**Comment by Yamagi** [comment]
9fa0f12 look good. Thank you. Can you squish it with 6851e35, c65c464  and 6851e35? Then it woul be perfect. :)

A bigger problem is, that the games crashes for me sometimes in sw_image.c line 174. I think, but that's just an educated guess, that the buffer at `image->pixel[0]` is too small. The backtrace, the game was compiled with `-O0`, is:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
memcpy () at /usr/sources/12-STABLE/lib/libc/amd64/string/memmove.S:268
268		MEMMOVE erms=0 overlap=1 begin=MEMMOVE_BEGIN end=MEMMOVE_END
(gdb) bt
#0  memcpy () at /usr/sources/12-STABLE/lib/libc/amd64/string/memmove.S:268
#1  0x00000008021ff34c in R_LoadPic (name=0x7fffffffe280 "pics/m_main_video_sel.pcx", 
    pic=0x804e53000 "\377\377\377\377\377\377\377\377\377\216\001/..........--..-", '.' <repeats 12 times>, "------.-.-.--.", '-' <repeats 48 times>, "..--../\237\216", '\377' <repeats 15 times>, "\237-,+++++++++", '*' <repeats 14 times>, "+*+", '*' <repeats 14 times>, "\003*\003\003*\003*", '\003' <repeats 25 times>..., width=118, height=32, type=it_pic)
    at src/client/refresh/soft/sw_image.c:174
#2  0x00000008021fed41 in R_LoadImage (name=0x7fffffffe280 "pics/m_main_video_sel.pcx", 
    namewe=0x7fffffffe140 "pics/m_main_video_sel", ext=0x7fffffffe296 "pcx", type=it_pic)
    at src/client/refresh/soft/sw_image.c:354
#3  0x00000008021fec36 in R_FindImage (name=0x7fffffffe280 "pics/m_main_video_sel.pcx", type=it_pic)
    at src/client/refresh/soft/sw_image.c:431
#4  0x00000008021fbbf5 in RE_Draw_FindPic (name=0x7fffffffe410 "m_main_video_sel")
    at src/client/refresh/soft/sw_draw.c:45
#5  0x00000008021fc1c8 in RE_Draw_PicScaled (x=1206, y=715, name=0x7fffffffe410 "m_main_video_sel", scale=1)
    at src/client/refresh/soft/sw_draw.c:258
#6  0x0000000000276f6e in Draw_PicScaled (x=1206, y=715, pic=0x7fffffffe410 "m_main_video_sel", factor=1)
    at src/client/vid/vid.c:622
#7  0x000000000024f268 in M_Main_Draw () at src/client/menu/menu.c:637
#8  0x00000000002501a7 in M_Draw () at src/client/menu/menu.c:4428
#9  0x0000000000242622 in SCR_UpdateScreen () at src/client/cl_screen.c:1627
#10 0x000000000023aeab in CL_Frame (packetdelta=36745, renderdelta=36745, timedelta=36745, packetframe=true, 
    renderframe=true) at src/client/cl_main.c:807
#11 0x0000000000287924 in Qcommon_Frame (msec=36745) at src/common/frame.c:670
#12 0x00000000002870b6 in Qcommon_Mainloop () at src/common/frame.c:159
#13 0x0000000000287f12 in Qcommon_Init (argc=7, argv=0x7fffffffe7d8) at src/common/frame.c:370
#14 0x00000000002c3dfb in main (argc=7, argv=0x7fffffffe7d8) at src/backends/unix/main.c:118
```

**Comment by 0lvin** [comment]
@Yamagi Thank you, yep, old sw_image::R_LoadPic has error in size calculation. Should be fixed not. Commits are rebased.

**Comment by Yamagi** [comment]
Aaaand merged. Thank you!

**Pull request merged**
