### PR TITLE
Sync haptic feedback with sound track

### PR DESCRIPTION
**Pull request by 0lvin**
Sync haptic feedback with original delay/attack/fade/volume/length of sound and remove effect hard coded haptic effects.

### CODE REVIEW

**Comment by 0lvin** [comment]
@lazd Could you please check code?

**Comment by lazd** [comment]
@0lvin I can give it a test next week! Anything specific you want me to look at?

How can I reproduce the model preview icon bug you fixed?

**Comment by 0lvin** [comment]
@lazd Currently code uses hardcoded values of haptic feedback for effect duration and volume and it works only for hardcoded list of sound effects.

I have changed it to any sound in `misc/menu/*`, `weapons/*`, `player{s}/*/pain/*`, `player/step/*`, `player/land/*`. As result mostly any weapons has haptic feedback with volume and duration similar to sound effect. 

And need to check haptic feedback with different gamepad(i have noname device), is result intuitive and comfortable for user? Or too long/short/loud/insync to effects?

**Comment by Yamagi** [comment]
I finally gave it a try. This is much better than the old, hardcoded stuff. Very good work! Are you happy with this and can I merge it or should I wait?

**Comment by 0lvin** [comment]
Thank you.

I have no additional changes for now.

**Comment by lazd** [comment]
I didn't get a chance to try it, but it looks good to me!

**Comment by Yamagi** [comment]
Perfect. Thank you!

**Pull request merged**
