### PR TITLE
Pathtracing

### PR DESCRIPTION
**Pull request by LethalManBoob**
Okay Im sorry if this dosent belong here (im very new) but im trying to contact you about how to build this. Ill just say that the instructions are wrong and very broken.

Can you ether pleeeease precompile it for us standerd plebs or give us clear instructions on what to do.

### CODE REVIEW

**Comment by Yamagi** [comment]
Aeh, what? Yamagi Quake II binaries for Windows (and maybe OS X, depends on the community) can be found at https://www.yamagi.org/quake2/. Linux and BSD binaries in your distributions package manager. Pathtracing Quake II is another project that's based on our source. If want binaries for it go and ask them in their issue tracker.

**Comment by DanielGibson** [comment]
BTW, the build instructions work well, if you follow them.
They don't mention Visual Studio - because it's not supported.

The project you're looking for is https://github.com/eddbiddulph/yquake2

And you want to create an "issue", not a "pull request" - pull requests are for developers to submit source code improvements.

**Comment by LethalManBoob** [comment]
Sorry i have since gotten past this issue. i would have deleted this if i could. please delete this yamagi. thanks. :)

**Comment by DanielGibson** [comment]
yeah the problem with github is that pull requests and issues can't be deleted, for whatever reason. quite annoying, especially since this kind of thing happens occasionally (you're not the first :))

**Pull request closed without merging**
