### PR TITLE
frame cpu pause refactoring.

### PR DESCRIPTION
**Pull request by devnexen**
expanding to powerpc archs also for visual studio/MSVC while
keeping clang support for windows.

### CODE REVIEW

**Comment by turol** [comment]
This should be an inline function in the header. Adding function call overhead for a single instruction is kind of silly.

**Comment by devnexen** [comment]
You re right it seems it was not really the trend of the overall code doing so so I did not dare but definitively makes more sense.

**Comment by DanielGibson** [comment]
As it's only used in one place, it doesn't even have to be a function at all but could remain inline.

I'd even argue that it *should* remain inline, because with the change we'd have duplicated code in the two versions of system.c

**Comment by Yamagi** [comment]
And merged, thank you :)

**Pull request merged**
