### PR TITLE
fix attempt for #894

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by DanielGibson** [comment]
Could you explain how this change relates to the issue?
It's not really obvious from looking at the change ;)

**Comment by devnexen** [comment]
Sure. Well I could not reproduce however those global variables are affected [here](https://github.com/yquake2/yquake2/blob/2fae1662c2edcb8e2e2cd4739be57339bedd68d0/src/common/collision.c#L1894) I artificially reproduced having too large number :)

**Comment by DanielGibson** [comment]
But the code you changed is executed at **level load**, and Yamagis error was in **base1**, so we can rule out invalid map data (that would trigger your error), except maybe if he had data corruption either on his hard-disk or in RAM.

What I think really happened in #894:
It says `0x55da42f364df is located 1 bytes to the left of global variable 'phsrow'` - and `mask` is from `CM_ClusterPHS()` which always returns `phsrow`.
So the index used to access that array ways `-1` ("11 bytes **to the left**").
So `cluster = CM_LeafCluster(leafnum);` is -1. That can happen, it probably means that the cluster is invalid or non-existant or something like that.

Other code explicitly handles `CM_LeafCluster()` returning -1, for example the code you linked (`CM_ClusterPHS()` or `CM_ClusterPVS()` which then memsets the returned data to 0) or this code here: https://github.com/yquake2/yquake2/blob/2fae1662c2edcb8e2e2cd4739be57339bedd68d0/src/server/sv_world.c#L327-L330 (`clusters[i]` is set in line 290).

Anyway, the correct fix for the issue probably is to explicitly handle `cluster < 0` in `PF_inPHS()` and `PF_inPVS()`, to avoid a negative cluster-number from used as an index into the `mask` array.

**Comment by DanielGibson** [comment]
I pushed a fix: https://github.com/yquake2/yquake2/commit/4d6bdcc8530b1da3221e51a631e3e428faa88978

**Comment by devnexen** [comment]
ah right thx for the hint

**Pull request closed without merging**
