### PR TITLE
Fixed incorrect handling of - in late args and simplified code

### PR DESCRIPTION
**Pull request by BjossiAlfreds**
This PR addresses issue https://github.com/yquake2/yquake2/issues/757. It also greatly optimizes and shortens the code by skipping all the unnecessary string copying.

### CODE REVIEW

**Comment by DanielGibson** [comment]
Yamagi and me discussed this a bit, and there's still this issue I mentioned in #757:
> Are there legit usecases for - or at least + within an argv string? Like yquake2.exe +set game rogue+map whatever (without a space before +map that would turn rogue and +map into separate argvs)?

And while "legit" of course is always debatable, we fear that there's indeed .bat scripts from old mods and things like that which have a command without a space before the `+`.
While my example (`+set game rogue+map whatever`) would never have worked, because `Cbuf_AddEarlyCommands()` clears all `argv`s of `+set` and its arguments, `+map whatever+set r_fullscreen 0` would have worked before but not with this change.
So while the way you're doing it now is better code (and definitely is what id should have done in the first place - after all they basically do the same in `Cbuf_AddEarlyCommands()`), probably it would be better to keep the code like it was before (i.e. do that concatenation of the `argv`s) and only add special handling to the "skip `-`" case that makes sure to ignore `-` if the previous character is not a space

**Comment by DanielGibson** [comment]
I just pushed a minimal invasive fix - if you want you can try to rework your (cleaner) code to also support this case, but maybe the result would be even uglier than the current state

**Comment by BjossiAlfreds** [comment]
A lot of really weird stuff is possible with this game's strings if you try hard enough. The question is what can be reasonably expected to happen in practice, and I'm not sure if I share your concerns. If you can find 2-3 concrete examples of this then I'll stand corrected, but from where I stand I see no incentive for people to think that not separating arguments would even work, let alone do it for any other reason than typo.

But it's up to you guys in the end. I do think id's code can be simplified still, doing just one string build instead of two. I'd be happy to take on the challenge and update this PR.

**Comment by BjossiAlfreds** [comment]
My algorithm is pretty much completely unreworkable around having to build a string, so I just used your commit as a new base. I got rid of the build string and just called Cbuf_AddText directly for each scanned command. Not a big change or anything but then at least we get cleaner code, backwards compatibility and the bugfix all in one. Give this code a review and see if you can make it break (I couldn't).

And just to add to what I said above, you can't even chain early args together or it will break, so why someone would add a space between +set's but then decide to chain the late args (and that is without even knowing about early vs late args)... I don't even want to try to get into that frame of mind haha.

**Comment by Yamagi** [comment]
So, do we want this or not? :) To me the code looks good and so far I wasn't able to break it.

**Comment by Yamagi** [comment]
Mkay, we want it. Thank you! :)

**Pull request merged**
