### PR TITLE
Partial fixes for SDL3

### PR DESCRIPTION
**Pull request by erysdren**
I got it building and running with the current revision of SDL3. This PR is a draft because I haven't figured out how to fix `SDL_StartTextInput()` in `/src/client/input/sdl3.c` - it now requires an SDL_Window pointer, which can't gracefully be pulled from any of the renderers as far as I can see. I'm hoping for some guidance on that point.

Thanks,
erysdren

### CODE REVIEW

**Comment by protocultor** [comment]
I know it's just a draft, but as SDL3 is currently a work in progress, it would be really cool if you could mention the specific SDL commit your work targets. The "current revision" changes by the minute :)
Check #1136.
Your work feels worthy of being added to [this branch](https://github.com/yquake2/yquake2/tree/sdl3-20240811).

**Comment by erysdren** [comment]
Looks like the last time I rebuilt SDL3 on my machine was [a7bed81](https://github.com/libsdl-org/SDL/commit/a7bed810b3499d157655ae6dcc7cd5e8a34fa549)

**Comment by Yamagi** [comment]
> I got it building and running with the current revision of SDL3. This PR is a draft because I haven't figured out how to fix `SDL_StartTextInput()` in `/src/client/input/sdl3.c` - it now requires an SDL_Window pointer, which can't gracefully be pulled from any of the renderers as far as I can see. I'm hoping for some guidance on that point.

The SDL_Window is a global variable defined in the client in glimp_sdl3.c: https://github.com/yquake2/yquake2/blob/master/src/client/vid/glimp_sdl3.c#L55 Accessing it from the input backend isn't a problem. But what happens if we recreate the window? If text input must be reenabled every time it might be better to move the `SDL_StartTextInput()` call into `CreateSDLWindow()` and call unconditionally as soon as have a windows.

**Comment by erysdren** [comment]
@Yamagi any further changes needed? thanks!

**Pull request closed without merging**
