### PR TITLE
hunk api enrichment and micro optimisation on R_SetFrustum

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by DanielGibson** [comment]
all this code to get rid of *one* memset() (or, actually, move it to another function)?

**Comment by devnexen** [comment]
> all this code to get rid of _one_ memset() (or, actually, move it to another function)?

right, a bit overengineered indeed, removed.

**Comment by turol** [comment]
Typo in commit message

**Comment by Yamagi** [comment]
Thank you :)

**Pull request merged**
