### PR TITLE
Add UI to configure joystick sensitivity, support joystick expo

### PR DESCRIPTION
**Pull request by lazd**
## Changes

* Add support for `joy_expo` cvar with default value of `2` that makes joystick input non-linear. This enables both precise and fast movements, even at higher sensitivity levels.
* Adds a "customize joystick" sub-menu that provides sliders for changing the sensitivity and expo applied to joystick inputs.
* Allows setting mouse sensitivity to 0 in UI to work around a RetroPie bug where controller input was showing up as both joystick and mouse events

## More on expo

[This article](https://www.gamasutra.com/view/feature/130532/firstperson_control_design_for_.php) does a good job of explaining how this works.

image
**Left:** a linear yaw response. **Right:** an exponential yaw response.

Effectively, with this change, small movements make for fine aiming, big movements make for fast movement.

## Notes

Tested on RetroPie and it works great, the game is much more playable and I'm able to aim more accurately. I found I like the following settings:

```
set joy_expo "3.700000"
set joy_forwardsensitivity "1"
set joy_pitchsensitivity "0.550000"
set joy_sidesensitivity "1"
set joy_yawsensitivity "0.750000"
```

Additionally, adjusting the deadzones makes things much more accurate:

```
set joy_axis_leftx_threshold "0.025"
set joy_axis_lefty_threshold "0.025"
set joy_axis_rightx_threshold "0.025"
set joy_axis_righty_threshold "0.025"
```

### CODE REVIEW

**Comment by lazd** [comment]
@0lvin I didn't add UI for `joy_upsensitivity` as I wasn't sure exactly what it did since it's unused. I can easily add another slider, just say the word.

Additionally, I'm not sure how `joy_haptic_magnitude` works, so I didn't add UI for that either. Let me know the min, max, and step and I can add a slider for that too.

I also did not add UI for adjusting deadzones, but I would advocate that they are decreased by default at least to `0.10` or even `0.05`.

**Comment by 0lvin** [comment]
@lazd  `joy_upsensitivity` is used at [sdl.c#L714](https://github.com/yquake2/yquake2/blob/QUAKE2_7_45/src/client/input/sdl.c#L714) for calculate `joystick_up` that will be used for `upmove`at [sdl.c#L943](https://github.com/yquake2/yquake2/blob/QUAKE2_7_45/src/client/input/sdl.c#L943). Have I missed something?

About `haptic` - this option is showed only for joysticks with haptic feedback. Look to [menu.c#L1400](https://github.com/yquake2/yquake2/blob/QUAKE2_7_45/src/client/menu/menu.c#L1400) and [sdl.c#L1119](https://github.com/yquake2/yquake2/blob/QUAKE2_7_45/src/client/input/sdl.c#L1119)

**Comment by lazd** [comment]
@0lvin thanks for the reply, I installed the latest RetroPie on my Pi4 and I now have haptic support. I will move that slider until the `customize joystick` submenu.

Ok, I see what you mean about `upmove`, I will add a slider for it as well. Thanks!

**Comment by Yamagi** [comment]
Thank you for working on this. Merged.

**Pull request merged**
