### PR TITLE
game data packing representation of the headers

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by DanielGibson** [comment]
I'd suggest using a name like `savegameHeader_t` or similar instead of `savegame_t`, to make its purpose/meaning more clear.

**Comment by devnexen** [comment]
right that s just the headers after all :)

**Comment by Yamagi** [comment]
Can you do the same for xatrix and rogue? We try to keep baseq2 and bot official addons ins sync to make merging changes between them easier.

**Comment by DanielGibson** [comment]
ideally also zaero (the last time I changed something in the savegames I also did it there so it should be in about the same state as the official addons)

**Comment by devnexen** [comment]
ok done ... did not notice these repos until today :-) I guess that s too much to refactor in one repo like most of doom projects do.

**Comment by Yamagi** [comment]
> I guess that s too much to refactor in one repo like most of doom projects do.

And the licenses are incompatible. Quake II itself is under GPL2, the addons and most 3rd party mods are under the crappy SDK license. Some projects have merged baseq2, ctf, rogue and xarix into one. We won't do it, because it violates the SDL license and id Software, ZeniMax, Microsoft, whoever may not like that.

**Pull request merged**
