### PR TITLE
Shared models logic

### PR DESCRIPTION
**Pull request by 0lvin**
Additional code sharing between renders.

### CODE REVIEW

**Comment by 0lvin** [comment]
Code could be reviewed. I will create new PR if I have found some other copy paste 😃

**Comment by Yamagi** [comment]
From a source code point of view it looks good :) I will play through a few levels with this before merging this. I promise that it won't take as long as with the shared image load. I have again more time to spend and models aren't that complicated, because there aren't special cases like retexturing packs to test.

**Comment by Yamagi** [comment]
I have read through the code and nothing to complain. And I played some levels with all three renderers. Very good work! :) Can you rebase it on the latest master? Afterwards I'll merge it.

**Comment by 0lvin** [comment]
Thank you, rebased.

**Comment by Yamagi** [comment]
And merged :)

**Comment by Yamagi** [comment]
A test build for Windows is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20230121-2e939b1.zip

**Pull request merged**
