### PR TITLE
Implement accurate-aiming CVAR in baseq2 game code.

### PR DESCRIPTION
**Pull request by mjr4077au**
Awhile ago, I raised issue #379 about whether there was anything that could be done to improve the aiming in-game.

Essentially, I've taken this implementation from Berserker@QuakeII v1.41 that provides the accurate aiming I've desired for so long and placed it behind a CVAR so that it's not enabled by default.

I hope with this change being optional, it can be considered for merging into the port. There are many forum posts online about Quake II and how to get accurate aiming, so I believe this would be desirable by many players.

### CODE REVIEW

**Comment by Yamagi** [comment]
Wow, this is cool and looks good. Can you do the same for the xatrix and rogue addons? We try to keep all thre official games in sync. :)

**Comment by mjr4077au** [comment]
Yeah, sure! Let me take a look. I'll send separate PRs through per game since they're in split repositories.

**Comment by mjr4077au** [comment]
@Yamagi, I've implemented this option in all game code repositories that you host and have ensured they're all referenced in this PR for clarity.

Please let me know your thoughts once you've had a chance to test this out and whether anything further is needed :smile:.

**Comment by Yamagi** [comment]
Wow. Cool that you also did the unsupported mods / addons. Thank you very much, that's good work. :)

**Comment by mjr4077au** [comment]
No half-jobs here ;). Thanks for merging this all in!

**Pull request merged**
