### PR TITLE
Little simplification for NetBSD, /proc/<pid>/exe works just fine too.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by krytarowski** [comment]
Please use sysctl with KERN_PROC_PATHNAME,

**Comment by DanielGibson** [comment]
Can NetBSD use the same code as FreeBSD?

**Comment by krytarowski** [comment]
Almost yes, with different `name` values.

**Comment by DanielGibson** [comment]
Can you give an example for the name values?
Is this a new addition or has this always been supported? IIRC when we first wrote this (2015) the usual way for NetBSD was what we're doing there.

**Comment by krytarowski** [comment]
https://github.com/qemu/qemu/blob/master/util/oslib-posix.c#L383

`KERN_PROC_PATHNAME` is supported in all worth supporting releases.

**Comment by devnexen** [comment]
@krytarowski does it mean NetBSD plans to retire /proc at some point ?

**Comment by krytarowski** [comment]
It is kept for some compat with linux binaries, but not for native applications.

**Comment by Yamagi** [comment]
And merged. Thank you.

**Pull request merged**
