### PR TITLE
bus error fix when quitting. spotted on openbsd while

### PR DESCRIPTION
**Pull request by devnexen**
working ok on Linux and others.

### CODE REVIEW

**Comment by DanielGibson** [comment]
looks good, thanks!

(And this could only have worked by chance, ASan or valgrind would have complained as well. Yamagi says this code has only been merged recently and we missed this in the review)

**Comment by devnexen** [comment]
No problem I ve just noticed the indentation discrepancy sorry for that.

**Comment by DanielGibson** [comment]
just noticed, you fixed your own bug here, it was introduced by your earlier PR: https://github.com/yquake2/yquake2/pull/232 =)

**Comment by devnexen** [comment]
Very true :-) sorry for that I will be more careful if I ever do a new PR ;-)

**Comment by DanielGibson** [comment]
no problem, bugs happen, just thought it was funny :)

**Pull request merged**
