### PR TITLE
Makefile: Fix architecture detection on Windows

### PR DESCRIPTION
**Pull request by DanielGibson**
$PROCESSOR_ARCHITECTURE seems to contain the architecture of the host,
but we need the architecture the current MinGW shell is targeting.
$MINGW_CHOST seems to be just that, and on my system it's either
i686-w64-mingw32 (mingw32.exe) or x86_64-w64-mingw32 (mingw64.exe)
(No idea what it looks like for Windows on ARM...)

Now this is correctly set and also SSE is used for floating point math which fixes weird lightmap bugs we've been seeing.

### CODE REVIEW

**Comment by DanielGibson** [comment]
alternatively we could probably enforce SSE math on x86 (haven't tested that though)

**Comment by DanielGibson** [comment]
I'll change this to use SSE, also, as Yamagi pointed out, I'll have to look into savegame compatibility, as `$YQ2_ARCH` is used there and is now different (correct).

**Comment by DanielGibson** [comment]
done

**Comment by Yamagi** [comment]
And merged. Thank you!

**Pull request merged**
