### PR TITLE
Add resolution scaling to Vulkan renderer

### PR DESCRIPTION
**Pull request by rg3**
This commit adds a new cvar called vk_pixel_size that represents how big
pixels should look in the rendered world in order to simulate lower
screen resolutions. With its default value of 1 everything looks normal,
but with bigger sizes (e.g. 4) the rendered world starts to look
"pixelated" due to pixels appearing bigger.

To implement the effect, the viewport and scissor are modified when
drawing the world so the rendering results cover a smaller area in the
top-left corner of the image.

The post-processing fragment shader is used to scale the image back to
the swapchain size before drawing UI elements on top of it.

The UI is not affected by this change, so the existing UI scaling
options continue to work as before with no changes, adding some
flexibility to the mix.

Related to feature request #588.

### CODE REVIEW

**Comment by AnotherLife** [comment]
Interesting!! So what do values like 2 or 3 do?

**Comment by rg3** [comment]
> Interesting!! So what do values like 2 or 3 do?

It's similar, just less noticeable depending on the resolution, screen size, etc. vk_pixel_size determines the length of the square side in pixels. Value 1 means pixels are 1x1 squares (as usual), value 2 means they are 2x2, 3 means 3x3, 4 means 4x4, etc.

The following screenshots were taken with sizes 1, 2 and 4.

q2_0000
q2_0001
q2_0002

**Comment by DanielGibson** [comment]
> The world is still rendered in the chosen screen resolution and the game performs accordingly.

Wouldn't it make more sense to render at the appropriate lower resolution (e.g. 0.5*w, 0.5*h for `vk_pixel_size 2`) and scale that up to the real resolution in the postprocess step?
Should look the same, but have the advantage of additionally making rendering cheaper (maybe especially interesting once Vulkan support on Raspberry Pi is available in Raspbian)

(Might be more work though)

**Comment by rg3** [comment]
Indeed, it probably made more sense but I thought it would be much more complicated. However, I gave it a shot today and it turns out we can simply scale back the viewport and scissor when rendering the world and it works. I've updated the branch and the top comment.

**Comment by 0lvin** [comment]
Could you please add the new flag to a [documentation](https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#graphics-vulkan-only)?

**Comment by rg3** [comment]
Yes, added and updated branch.

**Comment by Yamagi** [comment]
@DanielGibson, are you okay with merging this?

**Comment by DanielGibson** [comment]
Oh sorry, totally forgot about this!
Yes, I think this looks good! :)

**Comment by Yamagi** [comment]
In that case: Merged! Thank you, @rg3!

**Pull request merged**
