### PR TITLE
cold attribute introduction proposal, applying for Sys_Error at first.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by DanielGibson** [comment]
Does this have any measurable performance impact?

**Comment by devnexen** [comment]
that is difficult to benchmark depends on the compiler and version, prioritising hot code paths and performance outcomes might differ case to case.

**Comment by Yamagi** [comment]
I don't think these changes are worth the (potential) hassle. Quake II runs more than fast enough on all systems build in the last 15 years, the only exception might be cheap some ARM boards. And those are more GPU than CPU limited. Introducing compiler (family) specific attributes to the code might give some small speedups that no one really needs, at the cost of much worse portability to other compiler families like MSVC. And it diverges us even more from other source ports.

**Comment by devnexen** [comment]
fair enough you re right

**Pull request closed without merging**
