### PR TITLE
Patch to ignore standard playback when Ogg support is enabled.

### PR DESCRIPTION
**Pull request by ewe2**
This patch is rebased on master and only affects Ogg playback if WITH_OLDPLAYBACK is set to no. CD playback if enabled will still exhibit the old behaviour ignoring that setting. We would have to alter the main source to do so. See pull request #95

### CODE REVIEW

**Comment by maraakate** [comment]
Why don't you just make it a CVAR?  Compile time flags for something this trivial doesn't make much sense to me?

**Comment by ewe2** [comment]
At least with this patch, the main source is untouched if people want a pristine version; if I added cvars I may as well prevent the CD code from triggering track 0 as well.

**Comment by maraakate** [comment]
It's up to Yamagi, but I think a CVAR would make more sense as it's something so small it's really not going to hurt anybody by having it as an option in the code.

**Comment by Yamagi** [comment]
I've merged the other version with a cvar

**Pull request closed without merging**
