### PR TITLE
Scale edge/surfaces/verts on outof....

### PR DESCRIPTION
**Pull request by 0lvin**
* Scale up allocated edge/surfaces/verts based on value in outof...
* Add check bounds for verts.
* Code style cleanups
* Fixed issue with disappeared train #281 
* Use common Mod_DecompressVis for all renders.

### CODE REVIEW

**Comment by DanielGibson** [comment]
I briefly tested it and it seems to work much better!
I only noticed one small glitch: In ware1 (same level as the train) right at the beginning there is this explodable crate, and from some view points it has a "hole" (but not from others):
q2_0075
q2_0077

**Comment by Yamagi** [comment]
Very good work. Thank you! If no one has objections we could merge ist.

**Comment by 0lvin** [comment]
@DanielGibson Issue should be fixed in cf4887c. Could you check?

**Comment by DanielGibson** [comment]
Yep, the glitch is fixed, great work!

**Comment by Yamagi** [comment]
Aaaand merged! :)

**Pull request merged**
