### PR TITLE
Add menu bitmap support and fixes for mod menu

### PR DESCRIPTION
**Pull request by apartfromtime**

### CODE REVIEW

**Comment by apartfromtime** [comment]
My apologies for the lack of commit message, I force pushed my commit message changes.

I can only cite quality of life improvements, this makes the code easier to interpret, and see how the retained mode menu functions. I intend to rewrite some of the menu system to be inline with that of q3ta, since the two systems only have minor differences.

**Comment by apartfromtime** [comment]
I can't do much more with this pull request as any more changes may conflict with pull request #827.

**Comment by Yamagi** [comment]
#827 was already merged. I didn't have time to review your pull request. Will do sometime next week.

I think we'll do another release 8.10 next weekend. To get some game fixes, the GL3 underwater effect and the GLES renderer lib out into the wild. This one will be merged afterwards, it's always a good idea to have at least some days cooldown time between the last changes and a release.

**Comment by apartfromtime** [comment]
I seem to have broken my commit history, when trying to merge changes from main. I'll resubmit.

**Pull request closed without merging**
