### PR TITLE
VSync on macOs build fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**
using native (but deprecated) OpenGL api instead of SDL on this
platform.

### CODE REVIEW

**Comment by devnexen** [comment]
did not refactor purposely gl3/gl1 there might be a reason I ignore.

**Comment by DanielGibson** [comment]
Are we sure that this fixes #745 ?

**Comment by devnexen** [comment]
I tried on an external TV but not a 120Hz, was hoping one of the folks testing it to confirm.

**Comment by devnexen** [comment]
seems not working out regarding the SDL2 topic.

**Pull request closed without merging**
