### PR TITLE
Small cleanup

### PR DESCRIPTION
**Pull request by 0lvin**
* small cleanup in soft render for make cppcheck happy
* reuse resize code in gl1 render

### CODE REVIEW

**Comment by Yamagi** [comment]
Was the ResizeSTB() stuff tested?

**Comment by 0lvin** [comment]
Yes, it used in soft render already.

I have checked it with vulkan and gl1 render - and have not found any visible issues.

**Comment by 0lvin** [comment]
@Yamagi What do you think about process all new code by [indent](https://www.gnu.org/software/indent/manual/html_node/indent_4.html#SEC4) to have common codestyle?

**Comment by DanielGibson** [comment]
> What do you think about process all new code by indent to have common codestyle?

No. That'd screw up `git blame` (you'd get the reformat commit instead of the commit introducing the "real" code change)

**Comment by 0lvin** [comment]
> No. That'd screw up git blame (you'd get the reformat commit instead of the commit introducing the "real" code change)

I mean only new code like vulkan render, where we have only several contributors and real author/commit of code lines before merge to master(stabilize) does not matter.

**Comment by 0lvin** [comment]
@Yamagi @DanielGibson Do you have some preferences for code style for **_ fully new code_**? Or style like **_linux kernel code_** from ident will be fine?

**Comment by Yamagi** [comment]
When I started YQ2 I put all code through uncrustify, the config is still here: https://github.com/yquake2/yquake2/blob/master/stuff/misc/uncrustify.cfg But in retroperspective I wouldn't do it again, I would leave the code indention and the file layout as they were. Merging is much, much easier when there aren't as little divergences as possible. I was young, inexperienced and didn't know that.

**Comment by 0lvin** [comment]
thank you

**Comment by Yamagi** [comment]
As style for new code: I'm more or less following FreeBSDs code style, https://www.freebsd.org/cgi/man.cgi?query=style&apropos=0&sektion=9&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html @DanielGibson does his own things. So something like the Linux kernel style should be okay.

**Pull request merged**
